### ISSUE TITLE
Smart spreadsheet

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/gaza-programme#2]
Hey @emilyb7!

Would it be possible for you to build a version of the smart spreadsheet for Gaza? Specifically, to pull their FCC/Code Wars/website data.

Thanks!

https://docs.google.com/forms/d/e/1FAIpQLSdeXWgSSl6uahj68ndUA72V2nQFUbQ--wHc_sP2HD9C_h830A/viewform?usp=sf_link

**Comment by emilyb7** [comment]
@rebeccaradding yup sure! Is there a deadline? I'm fairly free towards the end of this week.

Actually, what I want to do is to turn the script that I've been using until now into a kind of exportable library so that it can be used by anyone in the future and I don't have to rewrite everything every time. Not sure how realistic that is, but if it's at all possible, it would be more sustainable : )

**Comment by rebeccaradding** [comment]
@emilyb7 eeek, yes - @sofer, @RanaAlqrenawi and @saralk are conducting interviews in Gaza on June 5 and 6. Would it be possible to create something for this weekend that at least pulls their CodeWars, FCC, and creates a working website link?

Anything else you'd add, @saralk and @sofer?

**Comment by sofer** [comment]
@emilyb7 let me know if you want any clarification from me. Planning to spend some time today and tomorrow looking at applications.

**Comment by emilyb7** [comment]
@rebeccaradding @sofer i'm aiming to have this done today!

**Comment by emilyb7** [comment]
@sofer @rebeccaradding done! 

(see sheet called 'output')

There are considerably more errors / random output in the sheet this time. I think that's mostly because requirements haven't necessarily been met which means lots of invalid URLs. Let me know if you can think of any way to generally improve the presentation. Otherwise, hope everything's ok!

**Comment by emilyb7** [comment]
@sofer @rebeccaradding on a related note, I made this [this](https://script.google.com/macros/s/AKfycbwj_5W8oE5Xz-bzBBGqoV6yGVp1PmLDudqXamHUGfuemx1vX3gU/exec) which should allow anyone in future to set up the 'smart' spreadsheet by themselves.
If you have 2 mins, I'd really appreciate it if you could test it and see if it works for you!

**Comment by rebeccaradding** [comment]
@emilyb7 this is so exciting! Sorry it has taken so long for me to use it. I'm testing it out - but have realized the questions don't exactly match the order of the new application. Would you mind opening a new issue in `selection-committee` with this link so others can test it AND so that we can close this issue - seeing a discussion about selection during the scav hunt on the first day of FACG2...would not necessarily be amazing haha.

**Comment by emilyb7** [comment]
@rebeccaradding cool, glad you have tried it : ) The order of the questions shouldn't really matter. The idea is that the person using the tool can add / remove / sort the questions themselves. Happy to add in more explanation if you think that's necessary. In the meantime, I'll close this.
